### ISSUE TITLE
Comment on this approach.

### ISSUE THREAD

**Issue by JimCornelius** [TomasHubelbauer/puppeteer-globus-scraper#1]
I was trying to do what you're doing and came up with the same problems. But I have found a different solution. I inject pdfjsLib via script tags into the client then use the PdfViewer class in the DOM. This also means I don't have to navigate around the furniture of the viewer. I'm still tweaking my project so it's private on GitHub right now but will publish in a few days, holiday permitting.

**Comment by TomasHubelbauer** [comment]
Awesome! ❤️ Thank you for leaving this comment and I'll be looking forward to seeing your repo when it goes live 🙂

**Comment by JimCornelius** [comment]
I've just made my repository public  - https://github.com/JimCornelius/scrape-celex-sivs/

The bit you'll be interested in is where I inject pdfjs into the client-side. In this file:  https://github.com/JimCornelius/scrape-celex-sivs/blob/master/PdfSivParser.js

```
  async parsePdf(celexDoc, page) {
    this.celexDoc = celexDoc;
    this.page = page;

    // inject pdfViewerTags etc
    await page.evaluate(BrowserContext.injectPdfViewer);

    // inject some code into the webpage to help us out with PDFs
    await page.addStyleTag({ url: 'https://unpkg.com/pdfjs-dist@2.2.228/web//pdf_viewer.css' });
    await page.addScriptTag({ url: 'https://unpkg.com/pdfjs-dist@2.2.228/build/pdf.js' });
    await page.waitForFunction('pdfjsLib != undefined');

    await page.addScriptTag({ url: 'https://unpkg.com/pdfjs-dist@2.2.228/web/pdf_viewer.js' });
    await page.waitForFunction('pdfjsViewer != undefined');

    // calls loadPdfDoc in the browser context
    await page.evaluate(
      BrowserContext.loadPdfDoc,
      this.storage.Config.eurlex.pdfRoot + celexDoc.celexID,
      this.storage.Config.pdfjs.workerSrc,
    );
    // browser has control until ready to parse
    await this.readyToParseEmitted();
    // wait for parsing to complete and we're done for this page
    await this.parsePdfTags(this.collectElements());
  }
```
injectPdfViewer is evaluated in the browser context and is as follows:

```
  static injectPdfViewer() {
    document.addEventListener('textlayerrendered', (event) => {
      window.onDocEvent('textlayerrendered', event.detail.pageNumber);
    });

    // don't need existing body, replace it with the PdfViewer
    document.body.innerHTML = '';
    const pdfContainer = document.createElement('div');
    const viewer = document.createElement('div');
    document.body.appendChild(pdfContainer);
    pdfContainer.appendChild(viewer);
    pdfContainer.style = 'overflow: auto;position: absolute;width: 100%;height: 100%';
    pdfContainer.id = 'viewerContainer';

    viewer.id = 'viewer';
    viewer.className = 'pdfViewer';
  }

```

The whole pdf does not get loaded the viewer. It only holds only 2 pages of the TextLayer in the DOM at any one time. Once a page is scrolled into position it can be scraped. I scroll the pages into view by looking for the loading icon as follows:
  
```
static scrollPageIntoView(curPage) {
    const loadingIconTag = document.querySelector(`.page[data-page-number="${curPage}"] > .loadingIcon`);
    if (loadingIconTag) {
      loadingIconTag.scrollIntoView();
    }
  }
```

Once each page is scrolled into view and loaded I scrape for the tags I'm interested in and then get the next page, as below. Once I've scraped from all of the pages I can parse the scraped tags.

```
  async onDocEventAsync(event, val) {
    if (event === 'pagecount') {
      // this is a custom event, created when the callback of the
      // loadingTask.promise is called.
      //
      // On a large document there will pages where the text layer is not loaded into the DOM.
      // A <loadingIcon> element will exist in place of the span tags
      // As each loadingIcon is scrolled into view pdfJSLibe populates the textLayer.
      // We can then extract the tags to allow the page to be parsed.
      //
      // Scrolling a page out of view will remove the spans in the textlayer,
      // so the tags must be capturesd wthile the page is in view.
      // The container holds 2 pages at any one time on a normal scaled view.
      //
      // Only scroll new Pages into view after current text layer tags are captured

      this.pageTags = new Array(val).fill(null);
    } else if (event === 'textlayerrendered') {
      // text layer for page X is now in the DOM and can be parsed
      // capture the span tags in the current page
      this.pageTags[val - 1] = await this.getPageSpanElements(val);

      // find the next unrendered page and scroll it into view
      const nextPage = 1 + this.pageTags.indexOf(null);

      // keep at it while there are pages yet to render
      if (nextPage) {
        await this.page.evaluate(BrowserContext.scrollPageIntoView, nextPage);
      } else {
        // All pages rendered, we can now parse the whole PDF
        // emit a message to pass control back to func parsePdf awaiting
        this.storage.emitter.emit('readyToParse');
      }
    }
  }
```
I hope you find this useful.

Jim

**Comment by TomasHubelbauer** [comment]
This is pretty great, thanks! I took a good read through the code snippets in your comment as well as your repository as a whole and I plan on adopting your approach. Thank you again :-)

**Comment by TomasHubelbauer** [comment]
Hey @JimCornelius, I started playing around with Playwright (the Puppeteer alternative from Microsoft with support for controlling Chromium, Firefox and Webkit) and it turns out when you navigate to a PDF file in Firefox, it gives you access to the page running PDF.js to show the document. When you do that in Chrome, it crashes, so one needs to instrument the page with PDF.js first as you know. When using Firefox, all this work comes out of the box and it is still PDF.js, so I believe you code could be largely reduced and the selectors and parsing readiness detection logic unchanged! Let me know if you found this helpful.

Example: https://github.com/TomasHubelbauer/playwright-pdf
